### PR TITLE
Added peewee to the project instead of using plain sqlite3.

### PR DESCRIPTION
**Pull request by kalkehcoisa**
Replaced sqlite3 with peewee and added some files to be ignored in .gitignore.

### CODE REVIEW

**Comment by pgdagenais** [comment]
Building the sqlite database seems alot longer with peewee, can you look into that ?

**Peewee**

``` BASH
$ time stmcli
No data found, update? [y/n] y
Database Created
agency.txt
trips.txt
calendar_dates.txt
stops.txt
stop_times.txt
routes.txt

real    12m6.996s
user    9m23.042s
sys 0m20.298s
```

**sqllite3**

``` BASH
$ time stmcli -y
Database Created

real    1m55.949s
user    1m0.831s
sys    0m8.317s
```

**Comment by pboardman** [comment]
I'm also getting an error when trying to query a bus stop time:

`$ stmcli -s 54666 -b 141
Traceback (most recent call last):
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/bin/stmcli", line 4, in <module>
    __import__('pkg_resources').run_script('stmcli==1.0.3', 'stmcli')
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 742, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/pkg_resources/__init__.py", line 1504, in run_script
    exec(script_code, namespace, namespace)
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/stmcli-1.0.3-py3.5.egg/EGG-INFO/scripts/stmcli", line 133, in <module>
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/stmcli-1.0.3-py3.5.egg/EGG-INFO/scripts/stmcli", line 99, in main
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/stmcli-1.0.3-py3.5.egg/stmcli/bus.py", line 29, in next_departures
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/peewee-2.8.5-py3.5.egg/peewee.py", line 2197, in next
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/peewee-2.8.5-py3.5.egg/peewee.py", line 2257, in iterate
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/peewee-2.8.5-py3.5.egg/peewee.py", line 2423, in process_row
  File "/home/pgdagenais/git/stmcli/pr/stmcli/env/lib/python3.5/site-packages/peewee-2.8.5-py3.5.egg/peewee.py", line 2444, in follow_joins
KeyError: <class 'stmcli.models.Trip'>`

**Comment by kalkehcoisa** [comment]
@pgdagenais Yeah! The use of an orm is expected to make the queries slower because the orm means at least one new layer of processing to generate the query, instead of just inserting the data. But it seems too slow. I guess it would be better to keep using raw sql or use some tool like [csvkit](http://csvkit.readthedocs.io/en/latest/scripts/csvsql.html) to convert the data files directly to the database.
I'm going to take a look on it now.

**Comment by kalkehcoisa** [comment]
@Lacsap- Sorry! It must be my bad. I'm going to do a more proper check here.

**Comment by pboardman** [comment]
No problem, that's what the TravisCI tests are here for 😃

**Comment by kalkehcoisa** [comment]
@Lacsap- :smiley: I'm running the tests properly here right now. I was running test.sh with shell, instead of bash. No doubt why it was running so poorly.

@pgdagenais I guess one of things is the routine the check the max number of vars sqlite can handle in the machine. In my machine, the max vars of sqlite is low. Old machine, low resources, etc. It might be that it limits the search between zero to 100000. In your case, 100000 maybe too low. Don't know.
Tomorrow I'm going to better check it.

**Comment by kalkehcoisa** [comment]
I had to go out of the pure peewee and used sqlite3 directly to create the database and used some tunning. So it was possible to have a good performance without a huge memory consumption - and breaking my machine. ;)

**Comment by pboardman** [comment]
Very nice the query looks even faster than before! Would you mind just squashing some of your commit to make the commit history cleaner? Then I'll merge your changes. If you don't know how to do it there is some info [here](http://blog.steveklabnik.com/posts/2012-11-08-how-to-squash-commits-in-a-github-pull-request)

**Comment by kalkehcoisa** [comment]
A little late, but the rebase is done. Interesting command. I didn't know how to use it. Very hand. :)

Oh! Now that the changes are made I accidentally found out about this project http://www.sqlet.com/ .
Using it it's possible to query using sql over the text files, instead of having the trouble of converting them to a relational database. I haven't tried with big sets of data, with smaller ones it works fine and fast. It may be an option.

**Pull request merged**
